name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install -e .[dev]
      - run: refurb bong
      - run: pylint bong
  test:
    runs-on: large-runner
    steps:
      - uses: actions/checkout@v4
      - uses: ts-graphviz/setup-graphviz@v2
        with:
          ubuntu-skip-apt-update: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install -e .[dev]
      - uses: "google-github-actions/auth@v2"
      - run: pytest -n 16 --dist=loadfile # auto only launches 8 workers in CI, despite runners have 16 cores
