name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .[dev]
      - run: refurb bong
      - run: pylint bong
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .[dev]
      - uses: "google-github-actions/auth@v2"
      - run: pytest
